server:
  port : 12340
couchbase:
  hostname: "127.0.0.1"
  bucket: "product"
  userName: "root"
  password: "abc123"
spring:
  data:
    couchbase:
      auto-index: true
  webflux:
    base-path : "/api/v1"
  logging:
    level:
      org.springframework.data.couchbase.repository.query: DEBUG
product:
  page : 10
  defaultOffset : 1
  